# Python package build and test pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    python:
      python.version: '3.7'  # Only test with Python 3.7

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

# The following script step is removed as it installs dependencies from requirements.txt
# - script: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
#   displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines

  displayName: 'pytest'
